// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxVm3c9Xk4wPIXIRfzI35LUU_I7nWSBiE',
    appId: '1:40788674578:web:b1dff01a87409ba2df30cb',
    messagingSenderId: '40788674578',
    projectId: 'proyectocrud-f8c83',
    authDomain: 'proyectocrud-f8c83.firebaseapp.com',
    storageBucket: 'proyectocrud-f8c83.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABJ-gHHGRQhxORLBn3H93t6uHgDONNozc',
    appId: '1:40788674578:android:b4ce784f441c2352df30cb',
    messagingSenderId: '40788674578',
    projectId: 'proyectocrud-f8c83',
    storageBucket: 'proyectocrud-f8c83.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwVSUo4Ye1x02lBS6HZlShiY_GDOAxdHw',
    appId: '1:40788674578:ios:8e8a1e7e6f50b9d9df30cb',
    messagingSenderId: '40788674578',
    projectId: 'proyectocrud-f8c83',
    storageBucket: 'proyectocrud-f8c83.appspot.com',
    iosClientId: '40788674578-etj00i0opv3e9vrtf4ekf5hdbbm6qfia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwVSUo4Ye1x02lBS6HZlShiY_GDOAxdHw',
    appId: '1:40788674578:ios:8e8a1e7e6f50b9d9df30cb',
    messagingSenderId: '40788674578',
    projectId: 'proyectocrud-f8c83',
    storageBucket: 'proyectocrud-f8c83.appspot.com',
    iosClientId: '40788674578-etj00i0opv3e9vrtf4ekf5hdbbm6qfia.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterCrud',
  );
}
